# rustfmt.toml

# Basic formatting options
edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Unix"

# Import formatting
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Code style preferences
use_small_heuristics = "Max"
use_field_init_shorthand = true
format_strings = true
condense_wildcard_suffixes = true

# Control flow formatting
control_brace_style = "AlwaysSameLine"
else_trailing_comma = false
match_arm_blocks = true
match_block_trailing_comma = true
match_wildcard_trailing_comma = true

# Function and method formatting
fn_args_layout = "Tall"
fn_call_width = 100
fn_params_layout = "Tall"
fn_single_line = false

# Struct and enum formatting
struct_lit_single_line = true
struct_lit_width = 100
enum_discrim_align_threshold = 0
struct_field_align_threshold = 0

# Chain formatting
chain_width = 100
wrap_comments = false
comment_width = 100
normalize_comments = false
normalize_doc_attributes = false

# Array/collection formatting
array_width = 100
chain_indent = "Block"
combine_control_expr = true
overflow_delimited_expr = false

# Pattern matching
pattern_alignment_first_match = false
reorder_impl_items = false

# Advanced options
disable_all_formatting = false
error_on_line_overflow = false
error_on_unformatted = false
format_code_in_doc_comments = false
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
hard_tabs = false
hide_parse_errors = false
ignore = []
indent_style = "Block"
license_template_path = ""
make_backup = false
merge_derives = true
emit_mode = "Files"
required_version = "1.4.36"
skip_children = false
unstable_features = false
use_try_shorthand = false
use_block_indent = true